### ISSUE TITLE
cannot test multiple files with globbing pattern (*)

### ISSUE THREAD

**Issue by geekingfrog** [colinwren/grunt-ghost#14]
example of grunt config:

``` javascript
    ghost: {
      dist: {
        filesSrc: ['test/casper/*']
        options: {
          printCommand: true,
          printFilePaths: true
        }
      }
```

result:

```
File: [no files]
Command: casperjs test test/casper/*
Testing: test/casper/*
⚠  CasperError: Invalid test path: test/casper/*
```

If I run the command from the shell, everything works. If I specify the files with their name, it also works. I didn't find what was the error in the code :/

**Comment by colinwren** [comment]
Your right :frowning:

Hey @cbas do you think your recent commit could have broken this?

**Comment by sebdeckers** [comment]
I suspect so, though I haven't confirmed it. But is there any reason why this task doesn't follow the [conventional way to configure Grunt tasks](https://github.com/gruntjs/grunt/wiki/Configuring-tasks)? That's basically what I was trying to implement, and inadvertently broke the other config syntax.

**Comment by colinwren** [comment]
Your right that we should follow the convention, we should be able to make it work with the convention as well as maintain backwards compatibility. btw I added a release history so make sure to update that whenever you push to npm.

**Comment by sebdeckers** [comment]
What about doing a larger version bump to indicate the breaking change?

**Comment by colinwren** [comment]
Yeah, it should also log a message telling the user about the new syntax if they user `filesSrc`

**Comment by colinwren** [comment]
@cbas are you working on the code to fix this?

**Comment by sebdeckers** [comment]
Was awol this weekend- working on it now.

**Comment by colinwren** [comment]
@cbas I fixed it to support file globbing for the time being, but I agree we should do the major version bump and support the grunt convention like you said

**Comment by ecuan** [comment]
I'm getting this same error running on command from shell 
casperjs test /tests/client/*
⚠  CasperError: Invalid test path: /tests/client/*

But if I run it from test/client it does work...

any ideas?
