### ISSUE TITLE
Windows compatibility

### ISSUE THREAD

**Issue by sebdeckers** [colinwren/grunt-ghost#5]
#### Error

```
CreateProcessW: The system cannot find the file specified.
```
#### Problem

`require('child_process').spawn` does not find `casperjs` on Windows if it's in the `%PATH%` environment variable.
#### Suggestion

Use `grunt.util.spawn` instead.
See: https://github.com/gruntjs/grunt/wiki/grunt.util

**Comment by sebdeckers** [comment]
Alternatively, find the absolute `casperjs` path using [isaacs/node-which](https://github.com/isaacs/node-which/).

**Comment by colinwren** [comment]
Thanks! Thats a strange bug. I'll publish it to npm now.

**Comment by sebdeckers** [comment]
@colinwren You might want to check how this affects console output. I'm new to `grunt-ghost` and having trouble making a simple `console.log` from my test file show up in Grunt. Or am I supposed to use a different API to log messages from the test?

**Comment by colinwren** [comment]
Console output looks good to me, you should use [casper.log](http://casperjs.org/logging.html).

**Comment by sebdeckers** [comment]
Ah, found the cause: `grunt-ghost` does not yet support Grunt Multi Task style options. Will create a ticket/PR for that too. :heart: Thanks for creating this task btw!
