### ISSUE TITLE
NPM maintainer access

### ISSUE THREAD

**Issue by sebdeckers** [colinwren/grunt-ghost#9]
Hi Colin,

Thanks for the commit access. I'd like to also be able to `npm publish` those changes, unless you want to do it every time.

If you are comfortable with sharing this access, please run the following: `npm owner add seb grunt-ghost`

Alternatively please just run `npm publish` so that my latest changes go out as `1.0.8`.

Thanks,
Sebastiaan

**Comment by colinwren** [comment]
I added you on npm, I have been strictly following [node-semver](https://github.com/isaacs/node-semver) so when you publish make sure to continue that, also I made a quick smoke test that is a good quick check to see if its working but it is very rudimentary and needs more work to have good coverage. Thanks for all the great contributions!

**Comment by sebdeckers** [comment]
Thanks! I love how fast you respond to the PRs. :shipit:

**Comment by colinwren** [comment]
Haha yeah, I've been spending a lot of time on github recently
